spring:
  data:
    mongodb:
      # In Case of mongodb Repel Set
      #uri: mongodb://${MONGO_DB_HOSTNAME}:${MONGO_DB_PASSWORD}@mongod-0.mongodb:27017,mongod-1.mongodb:27017,mongod-2.mongodb:27017/users
      host: localhost
      port: 27017
      username: admin
      password: password
      database: users
      authentication-database: admin

server:
  port: 8081
